"""realiazando tirei o mini bio

Revision ID: e9e79f155c87
Revises: eb795addb411
Create Date: 2024-05-18 18:40:09.969833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e9e79f155c87'
down_revision = 'eb795addb411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tecnico', schema=None) as batch_op:
        batch_op.drop_column('mini_bio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tecnico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mini_bio', mysql.TEXT(), nullable=False))

    # ### end Alembic commands ###
